### ISSUE TITLE
Marker callback Closure

### ISSUE THREAD

**Issue by KonradHambuch** [webbingbrasil/filament-maps#11]
As I see marker callbacks can be Closures but they run on load of the map, not on marker click.

Example (modify footer on marker click):
```
Marker::make('end')
        ->lat($endLocation->coordLat)
        ->lng($endLocation->coordLon);   
        ->callback(fn() => $this->footer = $this->footer . "a" );
```
Now if I load the widget, the footer has so many 'a' letters as many markers there are on the map, but does not do anything on click of the marker.

I would like to dynamically load data (like show details under the map) about the place at that marker.

**Comment by dmandrade** [comment]
At the time, markers do not have the same functionality as Actions that can be executed in the backend when a click occurs.

the callback function is executed when the marker is rendered, its purpose is to provide a javascript that will be executed on the click event.

So, you can do your implementation using livewire's event/listeners:
```php
Marker::make('end')->callback('Livewire.emit("updateFooter", ' . json_encode($content) . ')');
```

Register event listener in map widget:

```php
protected $listeners = ['updateFooter' => 'showMarkerData'];

public function showMarkerData($data)
{
    $this->footer = new HtmlString($data);
}
```

Let me know if work

**Comment by KonradHambuch** [comment]
@dmandrade 

It does work but I don't really want to write html code in strings on server side. I also would like to put there buttons and such, which then must call the server api.

**Comment by dmandrade** [comment]
You can use blade views:

```php
protected $listeners = ['updateFooter' => 'displayMarkerDetails'];

public function displayMarkerDetails($placeId)
{
    $place = Place::find($placeId);
    $this->footer = view('marker-details', $place);
}
```

**Comment by KonradHambuch** [comment]
That is a good idea, but I still can't implement scripts in that blade view, because it can't find it. For example call a function on the onclick event of a button.
