### ISSUE TITLE
Issue with sticky header

### ISSUE THREAD

**Issue by invaders-xx** [webbingbrasil/filament-maps#12]
Hey,

I have an issue using the plugin [sticky-headers](https://filamentphp.com/plugins/sticky-headers): when scrolling down, the map goes over the header, see below

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/604907/198269735-139d047a-b849-4ed2-b400-efac0236c3e8.png">

**Comment by dmandrade** [comment]
Can you check if the changes on PR #13 fix the issue for you?

**Comment by invaders-xx** [comment]
@dmandrade yes it is ! Thanks
