### ISSUE TITLE
FullScreen page

### ISSUE THREAD

**Issue by ghost** [webbingbrasil/filament-maps#14]
Hello, excellent plugin. 

Is there any way of showing the map fullpage on a page view ? Without paddings or margins or any headers ?

Thank you.

**Comment by dmandrade** [comment]
In [v1.4.0](https://github.com/webbingbrasil/filament-maps/releases/tag/v1.4.0) two new actions were added to make the map fullpage or fullscreen.

Also, you can make the map fullscreen by default by setting the property `fullpage`

```php
class MyMap extends MapWidget
{
    protected bool $fullpage = true;
}
````
