### ISSUE TITLE
Multiple markers not rending

### ISSUE THREAD

**Issue by bitsmyth** [webbingbrasil/filament-maps#19]
**Describe the bug**
Returning an array of Markers does only render one in `getMarkers()`.

**To Reproduce**
```
<?php

namespace App\Filament\Widgets;

use Webbingbrasil\FilamentMaps\Actions;
use Webbingbrasil\FilamentMaps\Marker;
use Webbingbrasil\FilamentMaps\Widgets\MapWidget;

class Map extends MapWidget
{
    protected int | string | array $columnSpan = 2;

    protected bool $hasBorder = false;

    public function getMarkers(): array
    {
        $markers = [];
        $woodLots = auth()->user()->companies()->first()->woodLots()->with('location')->get();
        foreach ($woodLots as $woodLot) {
            $point = $woodLot->location->point;
            $markers[] = Marker::make('pos2')
                ->lat($point->getLatitude())
                ->lng($point->getLongitude())
                ->tooltip($woodLot->lot_number . ' ' . $point->getAltitude() . ' Höhenmeter')
                ->popup('Popup?');
        }

        return $markers;
    }

    public function getActions(): array
    {
        return [
        ];
    }
}

```

**Expected behavior**
Should load all markers and put it on the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/30150915/228896738-fda2e38c-bc41-4496-8b29-c2e091ea0f6d.png)

**Additional context**

**Comment by dmandrade** [comment]
You need to set a unique name for each Marker:

`Marker::make($woodLot->getKey) `

Let me know if this worked for you.

**Comment by bitsmyth** [comment]
Tahnks for your answer, the issue was that the name „pos2“ was always the same and got overwritten.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
