### ISSUE TITLE
Filament v3 support

### ISSUE THREAD

**Issue by mefenlon** [webbingbrasil/filament-maps#22]
## Describe the ideal solution or feature request
Filament 3 was released and the current filament-maps plugin is not compatible. 

> Problem 1
>     - Root composer.json requires filament/filament ^3.0-stable, found filament/filament[v3.0.0, ..., 3.x-dev] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - webbingbrasil/filament-maps is locked to version v1.4.3 and an update of this package was not requested.
>     - webbingbrasil/filament-maps v1.4.3 requires filament/filament ^2.16 -> found filament/filament[v2.16.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0-stable).

**Comment by vincent-tarrit** [comment]
Hello, i saw this fork : https://github.com/michaelklopf/filament-maps maybe a pull request could be made ? Thank you !

**Comment by d8vjork** [comment]
I'm actively working on this as a customer really needs this fixed.

Here is the repo I created: https://github.com/open-southeners/filament-maps/tree/test

**Make sure you add on the package version `dev-test` as I didn't want to affect main branch yet until fully tested**

Setup:

Add this piece on the bottom of your `dependencies` in your _composer.json_ file:

```json
"webbingbrasil/filament-maps": "dev-test"
```

Then this at the very bottom:

```json
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/open-southeners/filament-maps.git"
    }
]
```

**Comment by vincent-tarrit** [comment]
Hello ! Thank you for your work. I have this problem on your branch : 

Interface "Filament\Tables\Contracts\RendersFormComponentActionModal" not found

Do you know how to fix it ? Thank you !

**Comment by invaders-xx** [comment]
Interface "Filament\Tables\Contracts\RendersFormComponentActionModal" not found

Any updates @d8vjork ?

**Comment by d8vjork** [comment]
@invaders-xx I'll take a look if I have some time

**Comment by dmandrade** [comment]
I just released a beta release with Filament v3 support.
I tested all functions and drawing features.

Please, try [v3.0.0-beta.1](https://packagist.org/packages/webbingbrasil/filament-maps#v3.0.0-beta.1)
