### ISSUE TITLE
Using as a ressource widget and use $record

### ISSUE THREAD

**Issue by invaders-xx** [webbingbrasil/filament-maps#6]
Using the latest version I am not able to access the $record.
I use this widget in a resource's page view and like every other widgets you are able to access the record by declaring 
```php
public $record;
```
within the widget.
I build markers based on the record
```php
public function getMarkers(): array
    {
        return [
            Marker::make($this->record->id)->lat($this->record->latitude)->lng($this->record->longitude)->popup($this->record->city)
        ];
    }
```
and now $record is null

**Comment by dmandrade** [comment]
Fixed in v1.2.1
