### ISSUE TITLE
Readme default example has no height on Pages

### ISSUE THREAD

**Issue by KonradHambuch** [webbingbrasil/filament-maps#9]
If I install the plugin (1.3.1) and copy paste the Usage example, the widget has no height, although the readme says its set to 400px.

Looks like this:
![image](https://user-images.githubusercontent.com/48684304/196886210-0fcb2cb9-8a03-46c6-ac2a-98e59cc69d58.png)

**Comment by KonradHambuch** [comment]
It's not an actual bug, just you don't have to use php artisan make:filament-widget command, because it generates a view blade.php, which makes it empty... (maybe you should mention this in the readme :) )

**Comment by dmandrade** [comment]
Thanks for the tip, I'll put a note in the documentation..

**Comment by dmandrade** [comment]
Readme updated with a note about make command.
